LIB=   ax25

# AX.25
SRCS+=  ax25_pkt.c
SRCS+=  ax25_pkt_list.c

SRCS+=  ax25_plsm.c
SRCS+=  ax25_lmsm.c

# SRCS+=  ax25_dlsm.c

CFLAGS=         -I/usr/local/include -I../../lib/libbuf -I../../lib/libconn -I../../lib/libaxutil -I../../lib/libstr -Wall -Werror

MK_MAN=no

.include <bsd.lib.mk>
